### ISSUE TITLE
Crash on Profile View

### ISSUE THREAD

**Issue by padyx** [padyx/purplemoon-android#10]
```
#!java

java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.defiant.purplesky/ch.defiant.purplesky.activities.DisplayProfileActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2367)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3929)
at android.app.ActivityThread.access$900(ActivityThread.java:148)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5274)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:311)
at android.app.Activity.requestWindowFeature(Activity.java:3640)
at ch.defiant.purplesky.activities.common.BaseFragmentActivity.onCreate(BaseFragmentActivity.java:77)
at ch.defiant.purplesky.activities.common.AbstractTabbedActivity.onCreate(AbstractTabbedActivity.java:24)
at ch.defiant.purplesky.activities.DisplayProfileActivity.onCreate(DisplayProfileActivity.java:49)
at android.app.Activity.performCreate(Activity.java:5977)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2258)
... 11 more
```

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
resolved in be4a693
