### ISSUE TITLE
Crash when clicking on the "Loading" spinner of a list

### ISSUE THREAD

**Issue by padyx** [padyx/purplemoon-android#117]
* Postit
* Visits

```
#!java

java.lang.NullPointerException
at ch.defiant.purplesky.fragments.visits.VisitorFragment$OpenUserProfileListener.onItemClick(VisitorFragment.java:262)
at android.widget.AdapterView.performItemClick(AdapterView.java:299)
at android.widget.AbsListView.performItemClick(AbsListView.java:1282)
at android.widget.ListView.performItemClick(ListView.java:4450)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3181)
at android.widget.AbsListView$3.run(AbsListView.java:3932)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5633)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
Open for fixing
