### ISSUE TITLE
Crash in UploadService

### ISSUE THREAD

**Issue by padyx** [padyx/purplemoon-android#118]
Crash because AssetFileDescriptor implements Closeable, but not before 4.4 (Lvl 19)
```
#!java

java.lang.IncompatibleClassChangeError: interface not implemented
at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
at ch.defiant.purplesky.services.UploadService.upload(UploadService.java:127)
at ch.defiant.purplesky.services.UploadService.access$200(UploadService.java:38)
at ch.defiant.purplesky.services.UploadService$UploadRunnable.run(UploadService.java:89)
at java.lang.Thread.run(Thread.java:856)
```

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
(Revert milestone changed by renaming milestone)

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
Resolved in commit 5ef539d
