### ISSUE TITLE
Crash at rotating

### ISSUE THREAD

**Issue by padyx** [padyx/purplemoon-android#29]
Stacktrace:

{{{
#!plaintext

W/dalvikvm(28269): threadid=1: thread exiting with uncaught exception (group=0x40d84300)
E/AndroidRuntime(28269): FATAL EXCEPTION: main
E/AndroidRuntime(28269): java.lang.NullPointerException
E/AndroidRuntime(28269): 	at ch.defiant.purplesky.fragments.UserDetailsFragment.updateUI(UserDetailsFragment.java:58)
E/AndroidRuntime(28269): 	at ch.defiant.purplesky.activities.DisplayUserProfileActivity.updateWithUserBean(DisplayUserProfileActivity.java:109)
E/AndroidRuntime(28269): 	at ch.defiant.purplesky.activities.DisplayUserProfileActivity.access$2(DisplayUserProfileActivity.java:101)
E/AndroidRuntime(28269): 	at ch.defiant.purplesky.activities.DisplayUserProfileActivity$BeanLoaderTask.onPostExecute(DisplayUserProfileActivity.java:208)
E/AndroidRuntime(28269): 	at ch.defiant.purplesky.activities.DisplayUserProfileActivity$BeanLoaderTask.onPostExecute(DisplayUserProfileActivity.java:1)
E/AndroidRuntime(28269): 	at android.os.AsyncTask.finish(AsyncTask.java:631)
E/AndroidRuntime(28269): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E/AndroidRuntime(28269): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
E/AndroidRuntime(28269): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28269): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(28269): 	at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime(28269): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(28269): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(28269): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime(28269): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(28269): 	at dalvik.system.NativeStart.main(Native Method)

}}}

**Comment by padyx** [comment]
Original reporter is Bitbucket author 'dermitch'

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
Should not happen anymore in 0.3...

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
On hold for verification in 0.3

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
Did not occur again in current versions. marking as resolved

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
Adjust fix version

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'dermitch')
Happens on profile pages

1. Open profile
2. Open all tabs multiple times
3. Rotate device
4. Crash!
