### ISSUE TITLE
Crash: ClassCastException

### ISSUE THREAD

**Issue by padyx** [padyx/purplemoon-android#63]
From Android Dev Console

```
#!java

java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.defiant.purplesky/ch.defiant.purplesky.activities.MainActivity}: java.lang.ClassCastException: ch.defiant.purplesky.util.Holder cannot be cast to ch.defiant.purplesky.beans.UpdateBean
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4260)
at android.app.ActivityThread.access$700(ActivityThread.java:162)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:5777)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: ch.defiant.purplesky.util.Holder cannot be cast to ch.defiant.purplesky.beans.UpdateBean
at ch.defiant.purplesky.activities.MainActivity.onLoadFinished(MainActivity.java:553)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
at android.support.v4.app.LoaderManagerImpl$LoaderInfo.reportStart(LoaderManager.java:307)
at android.support.v4.app.LoaderManagerImpl.doReportStart(LoaderManager.java:768)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:581)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1231)
at android.app.Activity.performStart(Activity.java:5175)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2433)
... 12 more
```

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
Duplicate of #46.
