### ISSUE TITLE
Crash when users were searched with "around location"

### ISSUE THREAD

**Issue by padyx** [padyx/purplemoon-android#7]
When searching for users around the current location in user search and clicking on "use current location, the app crashes.

```
#!java

 Process: ch.defiant.purplesky, PID: 14392
    java.lang.ClassCastException: ch.defiant.purplesky.dialogs.ChooseLocationDialogFragment cannot be cast to ch.defiant.purplesky.customwidgets.ProgressFragmentDialog
            at ch.defiant.purplesky.fragments.SimpleUserSearchFragment.dismissProgressLocation(SimpleUserSearchFragment.java:266)
            at ch.defiant.purplesky.fragments.SimpleUserSearchFragment.locationObtained(SimpleUserSearchFragment.java:260)
            at ch.defiant.purplesky.fragments.SimpleUserSearchFragment.access$000(SimpleUserSearchFragment.java:41)
            at ch.defiant.purplesky.fragments.SimpleUserSearchFragment$1.deliverResult(SimpleUserSearchFragment.java:248)
            at ch.defiant.purplesky.fragments.SimpleUserSearchFragment$1.deliverResult(SimpleUserSearchFragment.java:243)
            at ch.defiant.purplesky.dialogs.ChooseLocationDialogFragment.returnResult(ChooseLocationDialogFragment.java:337)
            at ch.defiant.purplesky.dialogs.ChooseLocationDialogFragment$1.onClick(ChooseLocationDialogFragment.java:99)
            at android.view.View.performClick(View.java:5254)
            at android.view.View$PerformClick.run(View.java:21173)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6837)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
Fix crash on location obtained, resolves #121


→ <<cset d560dc282bc1>>
