### ISSUE TITLE
Crash when rotating device in Conversation

### ISSUE THREAD

**Issue by padyx** [padyx/purplemoon-android#9]
Crash on rotation
```
#!java

java.lang.NullPointerException: Attempt to invoke virtual method 'void ch.defiant.purplesky.adapters.message.MessageAdapter.clear()' on a null object reference
at ch.defiant.purplesky.fragments.conversation.ConversationFragment.showConversationWithUser(ConversationFragment.java:307)
at ch.defiant.purplesky.activities.chatlist.ChatListActivity.conversationSelected(ChatListActivity.java:120)
at ch.defiant.purplesky.fragments.ChatListFragment.openChatFragment(ChatListFragment.java:380)
at ch.defiant.purplesky.fragments.ChatListFragment.access$100(ChatListFragment.java:54)
at ch.defiant.purplesky.fragments.ChatListFragment$MessageListItemClickListener.onItemClick(ChatListFragment.java:67)
at android.widget.AdapterView.performItemClick(AdapterView.java:300)
at android.widget.AbsListView.performItemClick(AbsListView.java:1247)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3215)
at android.widget.AbsListView.onTouchUp(AbsListView.java:4021)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:3793)
at android.view.View.dispatchTouchEvent(View.java:8444)
...
```

**Comment by padyx** [comment]
(Original author of comment is Bitbucket user 'Chakotay')
ConversationActivity: Improve rotation handling. Resolve issue #113


→ <<cset a63187c3bdbd>>
